### ISSUE TITLE
Tweaker - API changes

### ISSUE THREAD

**Issue by Tec-h** [fentrasLABS/op-tweaker#1]
OpenPlanet API changes in 1.24.0 have changed enum values causing compilation to fail

from: CSystemConfigDisplay::ECSystemConfigDisplay__EZClip::_ZClip_Disable
to: CSystemConfigDisplay::EZClip::_ZClip_Disable

https://openplanet.dev/news/2022/api-changes-in-1-24-0

![fails_to_load](https://user-images.githubusercontent.com/25440964/174307319-30bb3440-ace8-4889-bd52-86613667abed.png)

**Comment by Tec-h** [comment]
> having the same issue of course. anyway to fix this ourselves or we just wait for an update?

You can of course install an earlier version of OpenPlanet.

**Comment by fentras** [comment]
Fixed in 9d1c09c8178f943da2ffc1aca26a6d1caba4e2e6. Thanks for reporting!
